version: "3.8"
services:
  frontend:
    image: node:20
    container_name: frontend
    ports:
      - 3000:3000
    working_dir: /gympass-frontend
    restart: always
    volumes:
      - ./frontend:/gympass-frontend
    command: bash -c "npm install && npm i -g nuxt && npm run dev"
    links:
      - backend
  backend:
    image: node:20
    container_name: backend
    restart: always
    working_dir: /gympass-backend
    ports:
      - 4000:4000
    volumes:
      - ./backend:/gympass-backend
    command: bash -c "npm install && npm i -g @nestjs/cli && npm run start:dev --inspect"
    links:
      - mysql
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: "gympass_db"
      MYSQL_USER: "user"
      MYSQL_PASSWORD: "password"
      MYSQL_ROOT_PASSWORD: "rootpassword"
    ports:
      - 3306:3306
