version: "3.8"
services:
  frontend:
    image: node:20
    container_name: frontend
    ports:
      - 3000:3000
    working_dir: /gympass-frontend
    restart: always
    volumes:
      - ./frontend:/gympass-frontend
    command: bash -c "npm install && npm i -g nuxt && npm run dev"
  backend:
    image: node:20
    container_name: backend
    network_mode: "host"
    restart: always
    working_dir: /gympass-backend
    ports:
      - 4000:4000
    volumes:
      - ./backend:/gympass-backend
    command: bash -c "npm install && npm i -g @nestjs/cli && npm run start:dev --inspect"
